baseURL = "https://seneca-engineering-students-society.github.io/ENG/"
publishDir = "docs"
relativeURLs = false
canonifyURLs = true
languageCode = "en-us"
title = "Engineering Society"
theme = "blowfish"


[params]
  description = "Engineering Society â€“ Events, projects, and community."
  colorScheme = "fire"
  defaultAppearance = "light"
  autoSwitchAppearance = true


