baseURL = "https://seneca-engineering-students-soceity.github.io/ENG/"
relativeURLs = true
canonifyURLs = true
languageCode = "en-us"
title = "Engineering Society"
theme = "blowfish"

publishDir = "docs"

[params]
  description = "Engineering Society â€“ Events, projects, and community."
  colorScheme = "fire"
  defaultAppearance = "light"
  autoSwitchAppearance = true

[params.assets]
  customCSS = ["css/custom.css"]
